name: Rails CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      sqlite:
        image: nouchka/sqlite3
        ports:
          - 5432:5432
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.0
        bundler-cache: true
    
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    
    - name: Set up database
      run: |
        bundle exec rails db:create
        bundle exec rails db:schema:load
    
    - name: Run tests and generate coverage
      run: |
        bundle exec rspec
    
    - name: Run security checks
      run: |
        bundle exec brakeman -q -w2
    
    - name: Run linting
      run: |
        bundle exec rubocop
  
  deploy:
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.0
        bundler-cache: true
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Install Elastic Beanstalk CLI
      run: |
        pip install awsebcli --upgrade --user
        echo "~/.local/bin" >> $GITHUB_PATH
    
    - name: Build for production
      run: |
        RAILS_ENV=production bundle exec rails assets:precompile
        
    - name: Create Elastic Beanstalk bundle
      run: |
        mkdir -p .elasticbeanstalk
        echo "branch-defaults:
          main:
            environment: GymManagementSystem-prod
        global:
          application_name: GymManagementSystem
          default_ec2_keyname: null
          default_platform: Ruby 3.3
          default_region: ${{ secrets.AWS_REGION }}
          sc: git" > .elasticbeanstalk/config.yml
        zip -r "deploy.zip" . -x "*.git*" "node_modules/*" "tmp/*" "log/*"
    
    - name: Deploy to Elastic Beanstalk
      run: |
        eb deploy GymManagementSystem-prod || eb create GymManagementSystem-prod
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
